### ISSUE TITLE
`@framelabs/pylon-client` is not in the (public) npm registry

### ISSUE THREAD

**Issue by felicio** [frame-labs/pylon-client#9]
## what

- `@framelabs/pylon-client` is not in the (public) npm registry
- ` ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@framelabs%2Fpylon-client: Not Found - 404`
- `error An unexpected error occurred: "https://registry.yarnpkg.com/@framelabs%2fpylon-client: Not found".`

## where

- https://www.npmjs.com/search?q=%40framelabs%2F

## how

- `pnpm install` or `yarn install` https://github.com/frame-labs/frame-extension

**Comment by felicio** [comment]
cc @mholtzman

**Comment by mholtzman** [comment]
thanks for reporting this @felicio. looks like this package got set to private. can you try now?

**Comment by felicio** [comment]
Done @mholtzman, thanks for fixing 🙏.
